[package]
name = "novaro-market-bot"
version = "0.1.0"
authors = ["Kasama <robertoaall@gmail.com>"]
edition = "2018"

[dependencies]
scraper = "0.10.0"
reqwest = "0.9.15"
telegram-bot-fork = "0.7.7"
mdo = "*"
